
#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum WINMODE { MODE_FULL, MODE_WIN };

	// Dynamic 컴포넌트 경우 매 프레임마다 갱신해야하는 컴포넌트 집단
	enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };

	enum INFO { INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };
	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

	enum INFO_TYPE {INFO_TYPE_POS, INFO_TYPE_ROT , INFO_TYPE_SCALE, INFO_TYPE_END};

	enum TEXTUREID { TEX_NORMAL, TEX_CUBE, TEX_END };

	enum RENDERID {
		RENDER_TILETEX ,  RENDER_MAPOBJECT_GROUND_DECOR, RENDER_MAPOBJECT_WALL_DECOR,
		RENDER_MAPOBJECT_OBSTACLE ,RENDER_MAPOBJECT_EVENT,
		RENDER_SKYBOX, RENDER_PRIORITY , RENDER_NONALPHA, RENDER_ALPHATESTING , RENDER_ALPHABLEND, RENDER_UI, RENDER_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum TRIANGLETYPE {TRIANGLE_X, TRIANGLE_Y, TRIANGLE_Z}; // 누구 축 기준으로 Vertex를 찍고 삼각형을 그렸는지 나누는 Enum 겂

	enum COLLIDERTYPE{ COLLIDER_NONE, COLLIDER_AABB, COLLIDER_AAABBB, COLLIDER_OBB, COLLIDER_SPHERE, COLLIDER_RAYCAST, COLLIDER_END};

	// 총 RAY, UI용 RAY, 지형타기 RAY, 
	enum RAY_TYPE {RAY_NONE, GUN_RAY, UI_RAY, MACE_RAY, PICKING_RAY, INTERACTION_RAY, EVENT_CUBE_RAY , EYEOFCHAOS_RAY,

		MAPTOOL_TILE_FLOOR_NONE_CLICK_RAY , MAPTOOL_TILE_CEILING_NONE_CLICK_RAY , MAPTOOL_TILE_FLOOR_CLICK_RAY , MAPTOOL_TILE_CEILING_CLICK_RAY , 

		MAPTOOL_CUBE_NONE_CLICK_RAY, MAPTOOL_CUBE_CLICK_RAY,
		
		MAPTOOL_TILE_FLOOR_NONE_CLICK_TEX_RAY, MAPTOOL_TILE_CEILING_NONE_CLICK_TEX_RAY, MAPTOOL_CUBE_NONE_CLICK_TEX_RAY, 
		MAPTOOL_TILE_FLOOR_CLICK_TEX_RAY,	   MAPTOOL_TILE_CEILING_CLICK_TEX_RAY ,     MAPTOOL_CUBE_CLICK_TEX_RAY,
		MAPTOOL_DELETE_NONE_CLICK_RAY, MAPTOOL_DELETE_CLICK_RAY, MAPTOOL_NONE_CLICK_INFO_RAY ,MAPTOOL_CLICK_INFO_RAY ,

		MAPTOOL_OBJECT_NONE_CLICK_RAY, MAPTOOL_OBJECT_CLICK_RAY,

		END_RAY
	};

	enum LOADINGID {LOADING_NONE =-1,  LOADING_TUTORIALSTAGE, LOADING_LOGO, LOADING_STAGE, LOADING_STAGE2, LOADING_BOSS, LOADING_BOSS2, LOADING_END };

	enum SOUNDCHANNEL 
	{
		SOUND_BGM,
		
		UI_SOUND,
		ITEM_SOUND,
		MONSTER_SOUND,
		INTERACTION_SOUND,
		EMBIENT_SOUND,
		EVENT_SOUND,
		BULLET_SOUND,
		PLAYER_SOUND,

		MAX_CHANNEL,
	};

	enum CAMERASTATE
	{
		CAM_NONE,
		CAM_FIRSTPERSON,
		CAM_THIRDPERSON,
		CAM_FREE,

		CAM_SHAKE,
		CAM_BOSS_CUTSCENE,
		CAM_CINEMATIC,
		CAM_BOSSORBITAL, // SR 이후로 삭제 범용성 X
		CAM_ORBITAL,
		CAM_ZOOM,
		CAM_ZOOMOUT,
		CAM_BOSS_TARGET,
		
		CAM_TOOLMODE,
		CAM_UIMODE,
		CAM_TOOLMODE_EFFECT
	};

	enum class KEY_TYPE
	{
		UP = VK_UP,
		DOWN = VK_DOWN,
		LEFT = VK_LEFT,
		RIGHT = VK_RIGHT,

		LSHIFT = VK_LSHIFT,
		RSHIFT = VK_RSHIFT,

		Q = 'Q', W = 'W', E = 'E', R = 'R', T = 'T', Y = 'Y', U = 'U', I = 'I', O = 'O', P = 'P',
		A = 'A', S = 'S', D = 'D', F = 'F', G = 'G', H = 'H', J = 'J', K = 'K', L = 'L',
		Z = 'Z', X = 'X', C = 'C', V = 'V', B = 'B', N = 'N', M = 'M',

		// 키보드 숫자 (위쪽 숫자 키)
		NUM1 = '1', NUM2 = '2', NUM3 = '3', NUM4 = '4', NUM5 = '5',
		NUM6 = '6', NUM7 = '7', NUM8 = '8', NUM9 = '9', NUM0 = '0',

		F1 = VK_F1, F2 = VK_F2 , F3 = VK_F3 , F4 = VK_F4 , F5 = VK_F5 , F6 = VK_F6 , F7 = VK_F7 , F8 = VK_F8 , F9 = VK_F9 , F10 = VK_F10 ,


		K1 = VK_NUMPAD1, K2 = VK_NUMPAD2, K3 = VK_NUMPAD3, K4 = VK_NUMPAD4, K5 = VK_NUMPAD5, K6 = VK_NUMPAD6, K7 = VK_NUMPAD7,
		K8 = VK_NUMPAD8, K9 = VK_NUMPAD9,
		
		LBUTTON = VK_LBUTTON, RBUTTON = VK_RBUTTON, SPACE = VK_SPACE, TAB = VK_TAB,
	};

	enum class KEY_STATE
	{
		NONE,
		PRESS,
		DOWN,
		UP,
		K_END
	};

	enum OBJORIGINTYPE {ORIGIN_STATIC, ORIGIN_DYNAMIC};
	 
	enum OBJTYPE
	{
		OBJ_PLAYER, 
		OBJ_TILE, OBJ_CUBE, OBJ_TERRAIN, OBJ_GRID, OBJ_EVENTCUBE , 
		
		OBJ_MONSTER, OBJ_MONSTER_GOBLIN_HAMMER, OBJ_MONSTER_GOBLIN_FIREBALL, OBJ_MONSTER_ORGE_AXE, OBJ_MONSTER_RAT, OBJ_MONSTER_WIZARD, OBJ_MONSTER_SKELETON_SWORD,

		OBJ_MONSTER_BOSS, OBJ_EFFECT_BOSS_APPEAR, OBJ_MONSTER_BOSS_CLONE, OBJ_BARRIER, OBJ_BOSS_EFFECT, 

		OBJ_BULLET, OBJ_DOOR,


		OBJ_MAPDECOR  , OBJ_MAPOBSTACLE  , OBJ_MAPEVENT , OBJ_ITEM , OBJ_LIGHT,
		
		OBJ_PARTICLE, OBJ_PARTICLE_SYSTEM, OBJ_PARTICLE_SYSTEM_BLOOD, OBJ_PARTICLE_SYSTEM_SPARKLE, OBJ_PARTICLE_SYSTEM_ICE, OBJ_PARTICLE_SYSTEM_RAIN, OBJ_PARTICLE_SYSTEM_BUSH, OBJ_PARTICLE_SYSTEM_BARREL, OBJ_PARTICLE_SYSTEM_BOOK, OBJ_PARTICLE_SYSTEM_EAT, OBJ_PARTICLE_SYSTEM_BONE, OBJ_PARTICLE_SYSTEM_BROKENCUBE,
		
		OBJ_FOG, OBJ_FOG_SYSTEM, OBJ_CREATURECANTGO, 

		OBJ_UI, OBJ_SKYCUBE, OBJ_NONE, OBJ_END,
	};

	enum PROTOTYPE
	{
		PROTO_TRICOL, PROTO_RECTCOL, PROTO_CUBECOL, PROTO_PLANECOL, PROTO_TERRAINCOL, PROTO_GRIDCOL ,PROTO_CENTERLINECOL,

		PROTO_TEXTURE, PROTO_RECTEX, PROTO_TERRAINTEX, PROTO_CUBETEX, PROTO_CUBENETTEX, PROTO_UIRECTEX, PROTO_PARTICLERECTEX, PROTO_PARTICLEONFLOORTEX, PROTO_UITILETEX, PROTO_PARTICLERECTEX_ALPHA, PROTO_BOSS_APPEAR_MESH_TEX, 
		
		PROTO_MAPOBJECTTEX, PROTO_SKYCUBETEX,

		PROTO_TILETEX, PROTO_TRANS, PROTO_MOVEMENT, PROTO_CAMERA, PROTO_BILLBOARD, PROTO_ANIMATION, PROTO_STATUS, PROTO_WEAPON, PROTO_DOOR, PROTO_HOVERITEM, PROTO_DROPITEM, PROTO_MESH_ANIMATION, PROTO_BOSS_EFFECT_ANIMATION,

		PROTO_WALLET, PROTO_BARRIER,

		PROTO_COLLIDER_AABB, PROTO_COLLIDER_AAABBB, PROTO_COLLIDER_OBB, PROTO_COLLIDER_SPHERE,
	};

	enum WEAPONSTATE
	{
		WEAPON_MACE, WEAPON_GUN, WEAPON_ICEWAND, WEAPON_FIREWAND, WEAPON_FIRERING,

		WEAPON_GOBLIN_FIREBALL, WEAPON_ORGE_AXE, WEAPON_GOBLIN_HAMMER, WEAPON_RAT, WEAPON_SKELETON_SWORD, WEAPON_WIZARD,
		
		WEAPON_TRAP_FIREBALL,

		WEAPON_SKELLETON_SILVER_ARROW, WEAPON_SKELLETON_GOLD_ARROW,
		
		WEAPON_BOSS_THUNDER_DROP, WEAPON_BOSS_WIND, WEAPON_BOSS_ICEPILLAR, WEAPON_BOSS_ICEBALL, WEAPON_END,
	};

	enum BULLETSTATE
	{
		BULLET_NONE = -1,

		BULLET_PLAYER_CHARGEEMACE, BULLET_PLAYER_GUN, BULLET_PLAYER_GUNSKILL, BULLET_PLAYER_ICE, BULLET_PLAYER_FIREBALL, BULLET_PLAYER_EMBER,

		BULLET_GOBLIN_FIREBALL, BULLET_ORGE_AXE, BULLET_GOBLIN_HAMMER, BULLET_RAT, BULLET_SKELETON_SWORD, BULLET_WIZARD,
		
		BULLET_SKELLETON_SILVER_ARROW, BULLET_SKELLETON_GOLD_ARROW,

		BULLET_TRAP_FIREBALL,

		BULLET_BOSS_ICEBALL, BULLET_BOSS_ICEPILLAR, BULLET_BOSS_THUNDER_DROP, BULLET_BOSS_WIND
	};

	enum DOORTYPE { NONE_DOOR, ROOM_DOOR, 
		
		DEFAULT_WOOD_DOOR, DEFAULT_IRON_DOOR,

		SWITCH_WOOD_DOOR, SWITCH_IRON_DOOR,
		
		BRONZE_DOOR, SILVER_DOOR, GOLD_DOOR, BOSS_DOOR
		
		};

	enum STATUSEFFECT { STAT_NONE, STAT_FROZEN, STAT_BURN, STAT_POISION, STAT_END };

	enum MONSTERRANK {RANK_COMMON, RANK_RARE, RANK_EPIC, RANK_BOSS};

	enum SCENETYPE
	{
		LOGO,
		TITLE,
		LOADING,
		MAIN,
		TUTORIAL,
		STAGE1,
		STAGE2,
		BOSS,
		BOSS2,

		SCENE_END
	};

	enum FLOOR
	{
		FLOOR_B3 = 0,
		FLOOR_B2 = 1,
		FLOOR_B1 = 2,
		FLOOR_GROUND = 3,     // 지상 0층 (예: 로비)
		FLOOR_1F = 4,
		FLOOR_2F = 5,
		FLOOR_3F = 6,
		FLOOR_END,
	};

	enum ROOM
	{
		ROOM_NONE = -1, // 초기 값()

		ROOM0 = 0, // 밖 (외부)
		ROOM1, ROOM2, ROOM3, ROOM4, ROOM5, ROOM6, ROOM7, ROOM8, ROOM9,

		ROOM_END,
	};



	enum class TOOLTYPE
	{
		TOOL_NONE,
		TOOL_MAP,
		TOOL_OBJECT,
	};


	enum TILETYPE
	{
		TILE_NONE,
		TILE_FLOOR, // 바닥
		TILE_CEILING, // 천장
		TILE_END,
	};

	enum ITEMTYPE
	{
		ITEM_NONE,
		// 체력 + Armor
		ITEM_BERRIES, ITEM_HEALTH_SHARD, ITEM_ARMOR_SHARD, ITEM_GREATER_POTION,	// 회복 샤드 (+2), 포션 (+25)

		// 돈
		ITEM_BROZE_COINS, ITEM_SILVER_COINS, ITEM_GOLD_COINS, ITEM_COIN_PURSE, ITEM_GOLD_CHALICE, // 동 코인 (+15), 실버 코인(+25), 금 코인 (+50), 돈 자루(+45), 성배 (+75) 

		// 무기류
		ITEM_FIREBALL_RING, ITEM_ICEWAND, ITEM_GUN,	// 아이템 해금

		// 총알류
		ITEM_LOW_MANA ,ITEM_FIRE_SHARD, ITEM_ICE_SHARD, ITEM_GUN_BULLET,		// 총알 + 12

		// 열쇠류
		ITEM_BRONZE_KEY, ITEM_SILVER_KEY, ITEM_GOLD_KEY, ITEM_TREASURE_KEY,

		ITEM_COUNT_END,
	};

	enum MAPTOOL_BUILDTYPE
	{
		BUILD_NONE,
		BUILD_CREATE,
		BUILD_TEXTURE,
		BUILD_DELETE,
		BUILD_INFO,
		BUILD_END,
	};

	enum MAPTOOL_SHAPETYPE
	{
		SHAPE_NONE,
		SHAPE_TILE,
		SHAPE_CUBE,
		SHAPE_END,
	};

	enum MONSTER_TYPE
	{
		MONSTER_GOBLIN_HAMMER,
		MONSTER_GOBLIN_FIREBALL,
		MONSTER_ORGE_AXE,
		MONSTER_BOSS,
		MONSTER_RAT,
		MONSTER_SKELETON_SWORD,
		MONSTER_WIZARD,
		MONSTER_END
	};


	enum CUBE_FACE
	{
		CUBE_FACE_NEGATIVE_Z = 0,
		CUBE_FACE_POSITIVE_Z = 1,

		CUBE_FACE_NEGATIVE_X = 2,
		CUBE_FACE_POSITIVE_X = 3,

		//CUBE_FACE_NEGATIVE_Y = 4,
		CUBE_FACE_POSITIVE_Y = 4,

		CUBE_FACE_END,
	};

	enum CUBE_TYPE
	{
		CUBE_NONE = 0,
		CUBE_EVENT = 1,
		CUBE_MAPTOOL = 2,
		CUBE_CREATURECANTGO = 3,
		CUBE_UNKNOWN = 4,
	};

	enum BULLET_STATUS
	{
		BULLET_STATUS_IDLE,
		BULLET_STATUS_DEAD
	};

	enum MONSTER_STATUS
	{
		MONSTER_STATUS_SPAWN,
		MONSTER_STATUS_IDLE,
		MONSTER_STATUS_MOVE,
		MONSTER_STATUS_MOVE_IDLE,
		MONSTER_STATUS_JUMP,
		MONSTER_STATUS_ATTACK,
		MONSTER_STATUS_HIT,
		MONSTER_STATUS_ICE,
		MONSTER_STATUS_DYING,
		MONSTER_STATUS_ICE_DYING,
		MONSTER_STATUS_TELEPORT,
		MONSTER_STATUS_BUFF,
		MONSTER_STATUS_DYING_FOR_NEXT_PHASE,
		MONSTER_STATUS_DEAD,
		MONSTER_STATUS_END
	};

	enum PARTICLE_STATUS
	{
		PARTICLE_STATUS_INACTIVE,
		PARTICLE_STATUS_ACTIVE,
		PARTICLE_STATUS_END
	};

	enum PARTICLE_SYSTEM_STATUS
	{
		PARTICLE_SYSTEM_STATUS_INACTIVE,
		PARTICLE_SYSTEM_STATUS_ACTIVE,
		PARTICLE_SYSTEM_STATUS_END
	};

	enum PARTICLE_TYPE {
		PARTICLE_TYPE_TEST = 0,
		PARTICLE_TYPE_SPARKLE,
		PARTICLE_TYPE_GO_UP,
		PARTICLE_TYPE_DROP_ON_FLOOR,
		PARTICLE_TYPE_DROP,
		PARTICLE_TYPE_SMOKE,
		PARTICLE_TYPE_INIT_SMOKE,
		PARTICLE_TYPE_FLIES,
		PARTICLE_TYPE_RAIN,
		PARTICLE_TYPE_BROKENCUBE,
		PARTICLE_TYPE_END
	};

	enum CUBE_INDEX
	{
		//z -
		CUBE_INDEX_NEGATIVE_Z_LT = 0,
		CUBE_INDEX_NEGATIVE_Z_RT = 1,
		CUBE_INDEX_NEGATIVE_Z_RB = 2,
		CUBE_INDEX_NEGATIVE_Z_LB = 3,

		//z +
		CUBE_INDEX_POSITIVE_Z_LT = 4,
		CUBE_INDEX_POSITIVE_Z_RT = 5,
		CUBE_INDEX_POSITIVE_Z_RB = 6,
		CUBE_INDEX_POSITIVE_Z_LB = 7,

		//x -
		CUBE_INDEX_NEGATIVE_X_LT = 8,
		CUBE_INDEX_NEGATIVE_X_RT = 9,
		CUBE_INDEX_NEGATIVE_X_RB = 10,
		CUBE_INDEX_NEGATIVE_X_LB = 11,

		//x +
		CUBE_INDEX_POSITIVE_X_LT = 12,
		CUBE_INDEX_POSITIVE_X_RT = 13,
		CUBE_INDEX_POSITIVE_X_RB = 14,
		CUBE_INDEX_POSITIVE_X_LB = 15,

		////y -
		//CUBE_INDEX_NEGATIVE_Y_LT = 16,
		//CUBE_INDEX_NEGATIVE_Y_RT = 17,
		//CUBE_INDEX_NEGATIVE_Y_RB = 18,
		//CUBE_INDEX_NEGATIVE_Y_LB = 19,

		//y +
		CUBE_INDEX_POSITIVE_Y_LT = 16,
		CUBE_INDEX_POSITIVE_Y_RT = 17,
		CUBE_INDEX_POSITIVE_Y_RB = 18,
		CUBE_INDEX_POSITIVE_Y_LB = 19,

		CUBE_INDEX_END,
	};


	enum class MAPOBJECT_CATEGORY
	{
		DECOR,
		OBSTACLE,
		EVENT,
		ITEM,
		MONSTER,
		DOOR,
		LIGHT,
		_END,
	};

	enum class MAPOBJECT_PLACEMENT
	{
		GROUND, // 버퍼생성시 로컬 y좌표자체를 위로 올려버린다 로컬 중점이 대략? 0 0.5 0 
		WALL,	// 로컬 중점이 0 0 0
		_END,
	};


	enum class PropFlag : uint32_t {
		None = 0,
		Interactable = 1u << 0, // 상호작용 가능
		Destructible = 1u << 1,  // 파괴 가능
		Billbordable = 1u << 2,// 빌보드 적용
	};							

	enum class OBJECT_EVENT_TYPE
	{
		NONE = 0,
		INTERECT = 1,
		DOOR,
		CHAOSOFEYE,
		UNKNOWN,
	};

	enum class DOOR
	{
		DOOR_1,
		DOOR_2,
		DOOR_3,
		//
	};

	enum class EVENT_PATH
	{
		INTERECT_START = 0,

		ANTENAE,
		BARREL,
		BEERTABLE,
		CHICKENTABLE,
		BUSH,

		FLOWERBUSH,
		FLOWERPOT,
		LONGPOT,
		FATPOT,
		DUMMY,


		SWITCH,
		PHOTOSWITCH,
		SKULLSWITCH,

		CORPSE,

		CHEST,
		GOLDCHEST,
		WALLCHEST,

		ORB,
		ORBFIELD,

		BOOK,
		POUCH,

		WELL,
		
		BROKEWALL,

		INTERECT_END = 100,

		CHAOS,


		UNKNOWN,
	};


	enum class INTERACT_TYPE
	{
		UNKNOWN = 0,

		ANTENAE,
		BARREL,
		BEERTABLE,
		CHICKENTABLE,
		BUSH,

		FLOWERBUSH,
		FLOWERPOT,
		LONGPOT,
		FATPOT,
		DUMMY,

		SWITCH,
		PHOTOSWITCH,
		SKULLSWITCH,

		CORPSE,

		CHEST,
		GOLDCHEST,
		WALLCHEST,
		ORB,
		ORBFIELD,

		BOOK,
		POUCH,

		WELL,

		BROKEWALL,

		_END,
	};


	enum class RENDER_TYPE
	{
		ALL_RENDER,
		FLOOR_RENDER,
	};

	enum class CUBE_EVENT_TYPE
	{
		POSITION,
		PORTAL,//Door랑 같은거임	자체적으로 TargetPos를 들고있으면 될거같음 아마도?
		MOVE, // E를 눌러 상호작용을 하게 되면 CUBE가 움직여진다.
		DESTRUCTIBLE_ATTACK,
		DESTRUCTIBLE_GIMIC,
		_END,
	};


	enum class LIGHT_OBJECT_TYPE
	{
		NONE,
		CANDLE,
		CANDLETRIPLE,
		WALLTORCH,
		GROUNDTORCH,
		HANGINGBRAZIER,
		STATUE,
		CHANDELIER,
		FIREALTAR,
		UNKNOWN,
	};
}
#endif // Engine_Enum_h__